[package]
name = "d6-cmd"
version = "0.2.0"
edition = "2024"

[features]
trace = ["peg/trace"]

[dependencies]
getopts-macro = "0.1.8"
line-column = "0.1.6"
linked-hash-map = "0.5.6"
peg = "0.8.5"
rand = "0.9.2"
